version: '3.4'

services:
  superheroapi:
    image: ${DOCKER_REGISTRY-}superheroapi
    build:
      context: .
      dockerfile: SuperHeroAPI/Dockerfile
 
  superheroapi.database:
    image: postgres:latest
    container_name: SuperHeroAPI
    environment:
      - POSTGRES_DB=superheroapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


